---
- name: install lamp servers
hosts: all
become: yes
tasks:
  - name: update packages and install apache
    ansible.builtin.apt:
      name: apache2
      state: present
      update_cache: yes
  - name: update packages and install apache
    ansible.builtin.apt:
      name:
        - php
        - libapache2-mod-php
        - php-mysql
      state: present
  - name: copy infophp page
    ansible.builtin.copy:
      src: info.php
      dest: /var/www/html/info.php
  - name: restart apache2
    ansible.builtin.systemd:
      name: apache2
        state: restarted
        